### PR TITLE
Use scylla rust driver v0.9 pt 1)

### PR DESCRIPTION
**Pull request by louiscb**

### CODE REVIEW

**Comment by cleaton** [comment]
Hi @louiscb thanks for working on this. It’s something I’ve wanted to add as well, I’ve got some changes for the next branch but nothing ready to publish yet. 

A minor note, better make formatting change their own commit or even PR as mixing it with other changes makes it hard to review.

**Comment by louiscb** [comment]
Hi @cleaton, no worries! I accidentally made this PR to your repo instead of my fork, I wanted to test my upgrade to scylla 0.9 in production before making a proper PR to your repo. I'll take on board your formatting comment 👍

**Comment by cleaton** [comment]
@louiscb cool no problem. I’m curious what kind of production system are you working on?

**Comment by cleaton** [comment]
@louiscb I've pushed my updates to https://github.com/cleaton/ex_scylla/tree/next can see how we can merge these efforts.

**Comment by louiscb** [comment]
We are using scylla to write data from our web server which handles a large amount of traffic. Performance is key so we wanted to test if this Rust driver would be better than what we currently use which is erclass. I see that you made some benchmarks using Erlcass vs your new version of the scylla driver? How did it perform? I'll give it a try to run it locally myself in the next few days.

**Comment by cleaton** [comment]
from my testing erlcass still bit faster, but depending on workload ex_scylla might take the lead, especially if it's something that benefits from shard awareness. I wonder if 0.9 driver will make a difference. The tests helped me find improvement area in rustler: https://github.com/rusterlium/rustler/pull/482

**Comment by cleaton** [comment]
Ok i got my branch working again and had some time to experiments with the benchmarks again. Benchmarks without parallelism are faster but the more i push it the slower it gets. I'm still investigatin what is causing this bottleneck. 

@louiscb have you had any findings around this or other for your use case?

**Comment by louiscb** [comment]
Last week I tested my branch on our production servers and saw significantly worse performance than vs our current implementation with erlcass. I think it could be primarily be to do with the configurations however, since their default settings  and the way you configure each library and are very different there could be something I'm overlooking. 

Doing benchmarks as you are is probably a better first step than going straight into production though.

**Comment by louiscb** [comment]
@cleaton perhaps it would a good idea to open your branch as a PR or draft? That way we could discuss the specifics there.

**Comment by cleaton** [comment]
@louiscb I've created a draft PR and added a comment: https://github.com/cleaton/ex_scylla/pull/2

**Pull request closed without merging**
